# production mode
version: '3.5'
services:
  front_candidat:
    image: candilib_front_candidat:${APP_VERSION:-latest}
    container_name: ${CONTAINER_NAME_CANDIDAT:-candilib_front_candidat}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        CYPRESS_DOWNLOAD_MIRROR: ${CYPRESS_DOWNLOAD_MIRROR}
        NPM_AUDIT_DRY_RUN: ${NPM_AUDIT_DRY_RUN}
        CLIENT_BUILD_TARGET: candidat
        PUBLIC_PATH: /candilib
        APP_VERSION: ${APP_VERSION}
        LINE_DELAY: ${LINE_DELAY}
#    env_file:
#      - ${cnf:-.env}
    environment:
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-8000}
      LINE_DELAY: ${LINE_DELAY}
      API_USER_SCOPE: ${API_USER_SCOPE}
      API_USER_LIMIT_RATE: ${API_USER_LIMIT_RATE}
      API_USER_BURST: ${API_USER_BURST}
      APP_USER_LIMIT_RATE: ${APP_USER_LIMIT_RATE}
      APP_USER_BURST: ${API_USER_BURST}
    ports:
      - "${FRONT_CANDIDAT_PORT:-80}:80"
    restart: always
#    networks:
#      - candilib-network
  front_admin:
    image: candilib_front_admin:${APP_VERSION:-latest}
    container_name: ${CONTAINER_NAME_ADMIN:-candilib_front_admin}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        CYPRESS_DOWNLOAD_MIRROR: ${CYPRESS_DOWNLOAD_MIRROR}
        NPM_AUDIT_DRY_RUN: ${NPM_AUDIT_DRY_RUN}
        CLIENT_BUILD_TARGET: admin
        PUBLIC_PATH: /candilib-repartiteur
        APP_VERSION: ${APP_VERSION}
#    env_file:
#      - ${cnf:-.env}
    environment:
      API_HOST: ${API_HOST:-candilib_api}
      API_PORT: ${API_PORT:-8000}
      API_USER_SCOPE: ${API_USER_SCOPE}
      API_USER_LIMIT_RATE: ${API_USER_LIMIT_RATE}
      API_USER_BURST: ${API_USER_BURST}
      APP_USER_LIMIT_RATE: ${APP_USER_LIMIT_RATE}
      APP_USER_BURST: ${API_USER_BURST}
    ports:
      - "${FRONT_ADMIN_PORT:-80}:80"
    restart: always
#    networks:
#      - candilib-network

#networks:
#  candilib-network:
#    driver: bridge
#    driver_opts:
#      com.docker.network.driver.mtu: 1450
networks:
  default:
    external:
      name: ${APP}-network
