version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/server"
    update_schedule: "live"
    target_branch: "security"
    default_labels:
      - "security"
      - "dependencies"
      - "dependabot"

  - package_manager: "javascript"
    directory: "/client"
    update_schedule: "live"
    target_branch: "security"
    default_labels:
      - "security"
      - "dependencies"
      - "dependabot"
